### ISSUE TITLE
version mismatch with simplecov

### ISSUE THREAD

**Issue by chiperific** [traels-it/simplecov_badger#4]
In gemfile:

```ruby
gem "simplecov", "~> 0.22.0", require: false
gem "simplecov_badger", "~> 0.0.4", require: false
```

Leads to error:

```sh
#0 2.930 Could not find compatible versions
#0 2.930 
#0 2.930 Because every version of simplecov_badger depends on simplecov ~> 0.18.5
#0 2.930   and Gemfile depends on simplecov ~> 0.22.0,
#0 2.930   every version of simplecov_badger is forbidden.
#0 2.930 So, because Gemfile depends on simplecov_badger >= 0,
#0 2.930   version solving has failed.
```

**Comment by traels** [comment]
Hi @chiperific. Sounds like it's time for us to test this gem with newer simplecov versions :)
I'll see if I can find time this week - PR with fix is also welcome :)

**Comment by chiperific** [comment]
I wrote a fix that bumps the gems, and got the tests passing. LMK if we need more tests specific to later gem versions.

**Comment by chiperific** [comment]
I successfully used my fork of your gem on one of my repos and successfully got the badge, so not only are the tests passing, but I can confirm E2E on an app running simplecov v0.22
